@startuml Gerenciamento de Tarefas


left to right direction
:Usuário: as u
rectangle "Gerenciamento de Tarefas"{
    usecase "Login/Logout" as UC1
    usecase "Cadastro de Perfil" as UC2
    usecase "Cadastro de Tarefas" as UC3
    usecase "Edição de Tarefas" as UC4
    usecase "Exclusão de Tarefas" as UC5
    usecase "Arquivamento de Tarefas" as UC6
    usecase "Conclusão de Tarefas" as UC7
    usecase "Visualização de Tarefas" as UC8
    usecase "Cadastro de Categoria" as UC9
    usecase "Edição de Categoria" as UC10
    usecase "Exclusão de Categoria" as UC11
}   

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5
u --> UC6
u --> UC7
u --> UC8
u --> UC9
u --> UC10
u --> UC11



@enduml